import tkinter as GKMKK

KKKSFBKL = ("YOUR PC HAS BEEN" + " INFECTED!")#YUIYUINEYUIVNRT

import time as GSJGS#IOFVUIOJRFVUIOPJRESFUIOPJ
ANYIFYIOPFSYUIONASFYNUO = "J's"#KKFKFKAFKL:ASF
JAFJL12809381 = 5
RAVUIOraV = ("-to" + "pmost")
iAUVRFuVF = True

BJJKB = "bold"
JKKAKLKL = GSJGS.sleep
JKKAKLKL(JAFJL12809381)
IOARIOJMORVSUIORAVS = 1
DGUSDTPFVMUMDVUMPRSDVUM = "JKKKFKAS"
uAYUNYANUISDNUHSDA = 1 
def GGIJJG():
    LLBM = GKMKK.Tk()
    KKGM = LLBM.geometry


    JJMMLBXC = "Arial"#HHNHNHNI
    #UIOMUIOJMUIOMMIAUIHNFUNIFC

    KHAG = LLBM.title#N FADYUNAFVHN



    ANYIFYIOPFSYUIONASFYNUO
  #UUHFSSDFVUIOMUIODFVMUIODVUIOM
    KHAG("INFECTION")
    NBGMMB = LLBM.attributes
    ANYIFYIOPFSYUIONASFYNUO
    KKGM("500x50")
    ##*(H^*()H^&HYTYUIOASFVYUIOHNYUIOSFVN)
    NBGMMB(RAVUIOraV, iAUVRFuVF)#HYUSHNDFYUIHVNNFNHVJKFGE
    #IOGSYNUODGYUNYUINDGVYUIHNDGVYUINYUIONHNJHNJKVCHNJ
    #  #JKGSGVMUIJDGVMIOMJO:DGVJKMLJMKLKNMCVNXCxc
    label = GKMKK.Label(LLBM, text=KKKSFBKL, font=(JJMMLBXC, 20, BJJKB)) #OJK)$W$@$()*!$&*H><FN




    SDGMSDGUPOUGDS = label.pack
    ANYIFYIOPFSYUIONASFYNUO

#AFSDVMUIVMUIO:WERUIOAD:CVMMWRUOAHCMSHJKLNHCNXB ZC


    SDGMSDGUPOUGDS(pady=0, padx=10)#EJJEOJKJKEJKLJKLASDD

#IIOUMJUIOJMUIOUIOASUIOPDCMUIOPAJCMSDUMIODSC
    KKKSFBKL

    LLBM.mainloop()
#JKJJOIOJIOJIOJJOASYUOHNSDFYUIONVF SYUIN
while IOARIOJMORVSUIORAVS == uAYUNYANUISDNUHSDA: 
    GGIJJG() 